import type { FeedItem } from '../types/db'

// נתוני דמו להדגמת ה-DNA של הכתיבה (עובדה → הקשר → שורה תחתונה),
// ציון מהותיות, ודרגת מהימנות. יוחלפו בנתוני מאיה אמיתיים ב-Phase 1.
// מסודר לפי מהותיות יורדת — להדגים ש"החשוב צף, הרעש שוקע".
export const mockFeed: FeedItem[] = [
  {
    id: '1',
    source_id: 's-maya',
    source_name: 'מאיה',
    company_id: 'c-tsem',
    company_name: 'טאואר',
    security_id: null,
    title: 'טאואר מדווחת על רבעון שיא; הרווח הנקי זינק ב-13.7%',
    body: `טאואר פרסמה את דוחותיה הרבעוניים, ובהם רווח נקי הגבוה ב-13.7% מהרבעון המקביל אשתקד. ההכנסות עלו על רקע ביקוש מוגבר למוליכים למחצה אנלוגיים, והחברה העלתה את תחזית ההכנסות לשנה הקרבה.`,
    bottom_line: `המשך השיפור בשולי הרווח מחזק את ההערכות לעמידה ביעדי 2026 ותומך בתמחור הנוכחי של המניה.`,
    original_url: 'https://maya.tase.co.il/he/reports/companies/1082379',
    published_at: '2026-06-02T18:30:00+03:00',
    source_type: 'osint',
    reliability: 'verified',
    materiality_score: 9,
    direction: 'bull',
    status: 'published',
    is_public: true,
    lang: 'he',
    cluster_id: null,
    created_at: '2026-06-02T18:31:00+03:00',
    tags: ['מוליכים למחצה', 'דוחות כספיים'],
  },
  {
    id: '2',
    source_id: 's-press',
    source_name: 'עיתונות כלכלית',
    company_id: 'c-googl',
    company_name: 'אלפבית',
    security_id: null,
    title: 'אלפבית מגייסת 80 מיליארד דולר למימון תשתיות AI',
    body: `אלפבית הודיעה על תוכנית גיוס הון בהיקף 80 מיליארד דולר, מתוכם 10 מיליארד מברקשייר האת׳אווי בהנחה של 5% ממחיר הסגירה. זאת על אף יתרת מזומנים העולה על 100 מיליארד דולר. תחזית ההשקעות ההוניות לשנה עודכנה כלפי מעלה ל-190 מיליארד דולר.`,
    bottom_line: `ההחלטה לדלל הון חרף עתודות נזילות גבוהות מעידה על עומק מירוץ ההשקעות ב-AI, שצפוי לחצות טריליון דולר בקרב ענקיות הטכנולוגיה ב-2027.`,
    original_url: null,
    published_at: '2026-06-02T11:45:00+03:00',
    source_type: 'osint',
    reliability: 'reported',
    materiality_score: 8,
    direction: 'bear',
    status: 'published',
    is_public: true,
    lang: 'he',
    cluster_id: null,
    created_at: '2026-06-02T11:50:00+03:00',
    tags: ['טכנולוגיה', 'AI', 'גיוס הון'],
  },
  {
    id: '3',
    source_id: 's-maya',
    source_name: 'מאיה',
    company_id: 'c-shikun',
    company_name: 'שיכון ובינוי',
    security_id: null,
    title: 'הפניקס מכרה מניות שיכון ובינוי וירדה מתחת ל-8% מההון',
    body: `הפניקס דיווחה על מכירת מניות של שיכון ובינוי, שבעקבותיה ירדה החזקתה לכ-7.88% מהון החברה. המכירה בוצעה במסחר בבורסה לאורך התקופה האחרונה.`,
    bottom_line: `דילול החזקה של גוף מוסדי מרכזי עשוי להעיב על הביקוש למניה בטווח הקצר, אך אינו משנה את מבנה השליטה.`,
    original_url: 'https://maya.tase.co.il/he/reports/companies/1746514',
    published_at: '2026-06-02T20:33:00+03:00',
    source_type: 'osint',
    reliability: 'verified',
    materiality_score: 5,
    direction: 'neutral',
    status: 'published',
    is_public: true,
    lang: 'he',
    cluster_id: null,
    created_at: '2026-06-02T20:35:00+03:00',
    tags: ['נדל"ן', 'שינוי החזקות'],
  },
  {
    id: '4',
    source_id: 's-finint',
    source_name: 'נתוני שוק',
    company_id: 'c-tsem',
    company_name: 'טאואר',
    security_id: null,
    title: 'עסקת OTC בטאואר: מחיר חריג ב-5.5% משער הסגירה',
    body: `דווחה עסקה חריגה מחוץ לבורסה (OTC) במניית טאואר, בהיקף של כ-4 מיליון שקל, במחיר הנמוך ב-5.5% משער הסגירה האחרון.`,
    bottom_line: `עסקאות בודדות מחוץ לבורסה אינן מעידות בהכרח על מגמה, אך ריכוז עסקאות בהנחה מצדיק מעקב.`,
    original_url: null,
    published_at: '2026-06-02T18:00:00+03:00',
    source_type: 'finint',
    reliability: 'verified',
    materiality_score: 3,
    direction: 'neutral',
    status: 'published',
    is_public: true,
    lang: 'he',
    cluster_id: null,
    created_at: '2026-06-02T18:02:00+03:00',
    tags: ['מסחר', 'אנומליה'],
  },
]
